# Generated by Django 5.1.6 on 2025-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг (1-5)')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Место проживания',
                'verbose_name_plural': 'Места проживания',
            },
        ),
    ]
