# Generated by Django 5.1.6 on 2025-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_place_options_place_slug_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='dates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты пребывания'),
        ),
    ]
