# Generated by Django 5.1.6 on 2025-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_place_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
    ]
