# Generated by Django 5.1.6 on 2025-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_place_user_id_place_username_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='dates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты пребывания'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг (1-5)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='place',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
