# Generated by Django 5.1.6 on 2025-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('places', '0003_place_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='dates',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Даты пребывания'),
        ),
    ]
